### ISSUE TITLE
think u got the wrong package

### ISSUE THREAD

**Issue by jimmywarting** [AndreyJP/protractor-tests#1]
...Actually believe you meant to install standard and not standardjs

https://github.com/AndreyJP/protractor-tests/blob/bd49736442780e7fd804f9b9410a07c690137db2/package.json#L40

**Comment by AndreyJP** [comment]
Hi Jimmy Wärting! Thanks for your comment!

In fact, in this project I actually used standardjs (https://www.npmjs.com/package/standardjs). This project is a result of a course about Protractor.

Best Regards!
